CREATE DATABASE BIBLIOTECA_VENTAS
GO

USE BIBLIOTECA_VENTAS
GO

CREATE TABLE CLIENTE(
CLIE_ID INT,
CLIE_NOMBRE VARCHAR (100),
CLIE_TELEFONO INT,
CLIE_CORREO VARCHAR(100),
CLIE_DIRECCION VARCHAR(100),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIE_ID)
)

SELECT * FROM CLIENTE

CREATE TABLE EMPLEADO(
EMPL_ID INT,
EMPL_CEDULA INT,
EMPL_NOMBRE VARCHAR(100),
EMPL_TELEFONO VARCHAR(100),
EMPL_CORREO VARCHAR(100),
EMPL_DIRECCION VARCHAR(100),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (EMPL_ID)
)

CREATE TABLE GENERO(
GENE_ID INT,
GENE_NOMBRE VARCHAR(100),
CONSTRAINT PK_GENERO PRIMARY KEY (GENE_ID)
)

CREATE TABLE EDITORIAL(
EDIT_ID INT,
EDIT_NOMBRE VARCHAR(100),
EDIT_PAIS VARCHAR(100),
EDIT_CORREO VARCHAR(100),
EDIT_DIRECCION VARCHAR(100),
EDIT_TELEFONO INT,
CONSTRAINT PK_EDITORIAL PRIMARY KEY (EDIT_ID)
)

CREATE TABLE AUTOR(
AUTO_ID INT,
AUTO_NOMBRE VARCHAR(100),
AUTO_APELLIDO VARCHAR(100),
AUTO_PAIS VARCHAR(100),
CONSTRAINT PK_AUTOR PRIMARY KEY (AUTO_ID)
)

CREATE TABLE LIBRO(
LIBR_ID INT,
LIBR_NOMBRE VARCHAR(100),
LIBR_AUTO_ID INT,
LIBR_EDIT_ID INT,
LIBR_GENE_ID INT,
LIBR_PAGINAS INT,
LIBR_FECHA_LANZAMIENTO DATE,
LIBR_CANTIDAD INT,
LIBR_PRECIO_VENTA INT, 
LIBR_PRECIO_RENTA INT,
CONSTRAINT PK_LIBRO PRIMARY KEY (LIBR_ID),
CONSTRAINT FK_LIBR_AUTO FOREIGN KEY (LIBR_AUTO_ID) REFERENCES AUTOR(AUTO_ID),
CONSTRAINT FK_LIBR_EDIT FOREIGN KEY (LIBR_EDIT_ID) REFERENCES EDITORIAL(EDIT_ID),
CONSTRAINT FK_LIBR_GENE FOREIGN KEY (LIBR_GENE_ID) REFERENCES GENERO(GENE_ID)
)

CREATE TABLE TIPO_SERVICIO(
TISE_ID INT,
TISE_NOMBRE VARCHAR(5),
CONSTRAINT PK_TIPO_SERVICIO PRIMARY KEY (TISE_ID)
)

CREATE TABLE FACTURA(
FACT_ID INT,
FACT_CLIE_ID INT,
FACT_EMPL_ID INT,
FACT_FECHA DATE,
FACT_DESCUENTO INT,
FACT_TOTAL INT,
FACT_METODO_PAGO VARCHAR(50),
FACT_PAGO INT,
FACT_VUELTO INT,
CONSTRAINT PK_FACTURA PRIMARY KEY (FACT_ID),
CONSTRAINT FK_FACT_CLIE FOREIGN KEY (FACT_CLIE_ID) REFERENCES CLIENTE(CLIE_ID),
CONSTRAINT FK_FACT_EMPL FOREIGN KEY (FACT_EMPL_ID) REFERENCES EMPLEADO(EMPL_ID)
)

CREATE TABLE DETALLE_FACTURA(
DEFA_ID INT,
DEFA_FACT_ID INT,
DEFA_LIBR_ID INT,
DEFA_TISE_ID INT,
DEFA_CANTIDAD_LIBROS INT,
DEFA_CANTIDAD_PRESTAMO INT,
DEFA_PRECIO INT,
CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (DEFA_ID),
CONSTRAINT FK_DEFA_FACT FOREIGN KEY (DEFA_FACT_ID) REFERENCES FACTURA(FACT_ID),
CONSTRAINT FK_DEFA_LIBR FOREIGN KEY (DEFA_LIBR_ID) REFERENCES LIBRO(LIBR_ID),
CONSTRAINT FK_DEFA_TISE FOREIGN KEY (DEFA_TISE_ID) REFERENCES TIPO_SERVICIO(TISE_ID)
)

